spring.application.name=discuss

# ===============================
# Config database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/db_discuss
spring.datasource.username=root
spring.datasource.password=171005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update    
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Value
# ===============================
jwt.secret=5jGSBXEJQe0SXAlSplhiyP75Ex/whnwIqYumowsbj2UYx0PasariDeq+KFNRkPU3IWGR6ff7lq/z5HrPPJyEgA===
jwt.expiration.access.token=3600000
jwt.expiration.refresh.token=604800000
app.cookie.secure=true
app.cookie.same-site=Strict